sample = "TAGTCCGGGGAGCAGTTATCCGAGAAAACGAGCGCCGTCGCGGCGTGTAATAGCATGAGTAGTATCTTCGGTGAGGGATACTGTAAAATCCCCGGAGGAAGCACTTCAGCGGTGACCCGAAAACCTCCTGGATGACCTTCCAAAGAATTAACGCTCGTAGCAAACAGTTACTAAGTTCGGAGGGAAAGGAACAGGAAACGATACTCCAACCAGGACCGGCACTATGATTCACAAATCTGCCATACACCGCGGGGGCTAAACTGACGTACCTCGGGCGATTTTCCGAACTGTACCTCCGAAATAGTGGACCGACCCTCGTCGGAGAAAAACGAGGCGATCGAATGCGTTGCCTGTCGGAAGTCATATTCATGGCATCTTATAGGTGATCCGAGCACTCCCTGTTCGAGCATGACAATTTTGAGGCCAGTTACAGTCAACACAAGAAACGTTGGCCTCCAAGTGCGGTCCCAGGTATATTTTACAACGTCGAGGAAATTGCGCGAAGGTAGAGGTGCTTCATACGTCGGGATTATTGAGCACCGCTATACAAACAGGAAAGTGGTGTCGGTCAGGGGCGCCAGGACGCGCGAGGTCATCTGGGATGATAATTTGATCGCTCTAGATGTAAGGAGCTGATGTCCCCCTAACATAATAATCGCATACGATGGTCGCTACTCTCGCCAACTGCAGGTCCTCCAACACGTAGTCACGGTGAACCACTTAGGCGGTCCTTGTTGCTCAAAATTGTCAGCTAATGGCGCGGGAGGGGTGTAAGGTAAGAACACCTACGGCCGTCGTACCAAGCGATCGTGTCTTGAGCAACAGTGGGCTAACTTAGTTCGAAAGATGAGATTCTGTGTTGGTTTAGGACGAGCGGCTCACCGGTAGTCATCGTGTTTGAAATAGTCAGGCCGGGGTAAGGACTTCC"

#________________________________________________________________________________
# METODO 1

def count(DNA):
    A = 0
    C = 0
    G = 0
    T = 0
    for i in DNA:
        if i == "A":
            A = A + 1
        elif i == "C":
            C = C + 1
        elif i == "G":
            G = G + 1
        elif i == "T":
            T = T + 1

    return A, C, G, T

a, c, g, t = count(sample)
print(f"{a} {c} {g} {t}")



#________________________________________________________________________________
# METODO 2
def count2(DNA):
    A = DNA.count("A")
    C = DNA.count("C")
    G = DNA.count("G")
    T = DNA.count("T")
    return A, C, G, T

a2, c2, g2, t2 = count2(sample)
print(f"{a2} {c2} {g2} {t2}")


#________________________________________________________________________________
# METODO 3
def count3(DNA):
    bases = {
        "A": DNA.count("A"),
        "C": DNA.count("C"),
        "G": DNA.count("G"),
        "T": DNA.count("T")
    }
    return bases

dna_bases = count3(sample)
print(f"{dna_bases["A"]} {dna_bases["C"]} {dna_bases["G"]} {dna_bases["T"]}")